version: "3.8"

services:
  nginx:
    image: "nginx:1.25.3-alpine"
    container_name: laravel-nginx
    restart: unless-stopped
    depends_on:
      - php
      - postgres
      - adminer
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/app
  php:
    image: laravel/php
    build:
      context: dockerfiles
      dockerfile: Dockerfile-php
    container_name: laravel-php
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - env/php.env
    volumes:
      - ./src:/var/www/app
  postgres:
    image: postgres:16.0-alpine3.18
    container_name: laravel-postgres
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data
    env_file:
      - .env
  composer:
    container_name: laravel-composer
    image: laravel/composer
    build:
      context: dockerfiles
      dockerfile: Dockerfile-composer
    volumes:
      - ./src:/var/www/app
  artisan:
    container_name: laravel-artisan
    image: laravel/artisan
    build:
      context: dockerfiles
      dockerfile: Dockerfile-php
    env_file:
      - env/php.env
    volumes:
      - ./src:/var/www/app
    entrypoint: ["php", "/var/www/app/artisan"]
  adminer:
    image: adminer:4.8.1-standalone
    container_name: laravel-adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: nette
    ports:
      - "${ADMINER_PORT}:8080"
  pint:
    container_name: laravel-pint
    image: laravel/pint
    build:
      context: dockerfiles
      dockerfile: Dockerfile-php
    volumes:
      - ./src:/var/www/app
    entrypoint: ["php", "/var/www/app/vendor/bin/pint"]
  node:
    container_name: laravel-node
    image: laravel/node
    build:
      context: dockerfiles
      dockerfile: Dockerfile-node
    volumes:
      - ./src:/var/www/app
